/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PtShowDeTangoCafeTortoniRouteImport } from './routes/pt.show-de-tango-cafe-tortoni'
import { Route as EsShowDeTangoCafeTortoniRouteImport } from './routes/es.show-de-tango-cafe-tortoni'
import { Route as EnShowDeTangoCafeTortoniRouteImport } from './routes/en.show-de-tango-cafe-tortoni'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PtShowDeTangoCafeTortoniRoute =
  PtShowDeTangoCafeTortoniRouteImport.update({
    id: '/pt/show-de-tango-cafe-tortoni',
    path: '/pt/show-de-tango-cafe-tortoni',
    getParentRoute: () => rootRouteImport,
  } as any)
const EsShowDeTangoCafeTortoniRoute =
  EsShowDeTangoCafeTortoniRouteImport.update({
    id: '/es/show-de-tango-cafe-tortoni',
    path: '/es/show-de-tango-cafe-tortoni',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnShowDeTangoCafeTortoniRoute =
  EnShowDeTangoCafeTortoniRouteImport.update({
    id: '/en/show-de-tango-cafe-tortoni',
    path: '/en/show-de-tango-cafe-tortoni',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en/show-de-tango-cafe-tortoni': typeof EnShowDeTangoCafeTortoniRoute
  '/es/show-de-tango-cafe-tortoni': typeof EsShowDeTangoCafeTortoniRoute
  '/pt/show-de-tango-cafe-tortoni': typeof PtShowDeTangoCafeTortoniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en/show-de-tango-cafe-tortoni': typeof EnShowDeTangoCafeTortoniRoute
  '/es/show-de-tango-cafe-tortoni': typeof EsShowDeTangoCafeTortoniRoute
  '/pt/show-de-tango-cafe-tortoni': typeof PtShowDeTangoCafeTortoniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en/show-de-tango-cafe-tortoni': typeof EnShowDeTangoCafeTortoniRoute
  '/es/show-de-tango-cafe-tortoni': typeof EsShowDeTangoCafeTortoniRoute
  '/pt/show-de-tango-cafe-tortoni': typeof PtShowDeTangoCafeTortoniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en/show-de-tango-cafe-tortoni'
    | '/es/show-de-tango-cafe-tortoni'
    | '/pt/show-de-tango-cafe-tortoni'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en/show-de-tango-cafe-tortoni'
    | '/es/show-de-tango-cafe-tortoni'
    | '/pt/show-de-tango-cafe-tortoni'
  id:
    | '__root__'
    | '/'
    | '/en/show-de-tango-cafe-tortoni'
    | '/es/show-de-tango-cafe-tortoni'
    | '/pt/show-de-tango-cafe-tortoni'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnShowDeTangoCafeTortoniRoute: typeof EnShowDeTangoCafeTortoniRoute
  EsShowDeTangoCafeTortoniRoute: typeof EsShowDeTangoCafeTortoniRoute
  PtShowDeTangoCafeTortoniRoute: typeof PtShowDeTangoCafeTortoniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/show-de-tango-cafe-tortoni': {
      id: '/pt/show-de-tango-cafe-tortoni'
      path: '/pt/show-de-tango-cafe-tortoni'
      fullPath: '/pt/show-de-tango-cafe-tortoni'
      preLoaderRoute: typeof PtShowDeTangoCafeTortoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/show-de-tango-cafe-tortoni': {
      id: '/es/show-de-tango-cafe-tortoni'
      path: '/es/show-de-tango-cafe-tortoni'
      fullPath: '/es/show-de-tango-cafe-tortoni'
      preLoaderRoute: typeof EsShowDeTangoCafeTortoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/show-de-tango-cafe-tortoni': {
      id: '/en/show-de-tango-cafe-tortoni'
      path: '/en/show-de-tango-cafe-tortoni'
      fullPath: '/en/show-de-tango-cafe-tortoni'
      preLoaderRoute: typeof EnShowDeTangoCafeTortoniRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnShowDeTangoCafeTortoniRoute: EnShowDeTangoCafeTortoniRoute,
  EsShowDeTangoCafeTortoniRoute: EsShowDeTangoCafeTortoniRoute,
  PtShowDeTangoCafeTortoniRoute: PtShowDeTangoCafeTortoniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
